export enum OrderStatus {
    CREATED = 'CREATED',
    ACCEPTED_BY_RESTAURANT = 'ACCEPTED_BY_RESTAURANT',
    REJECTED_BY_RESTAURANT = 'REJECTED_BY_RESTAURANT',
    PREPARING = 'PREPARING',
    READY_FOR_PICKUP = 'READY_FOR_PICKUP',
    ASSIGNED_TO_COURIER = 'ASSIGNED_TO_COURIER',
    PICKED_UP = 'PICKED_UP',
    DELIVERING = 'DELIVERING',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED',
    PROBLEM = 'PROBLEM',
}
