export enum NotificationType {
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
    ORDER_ASSIGNED = 'ORDER_ASSIGNED',
    PAYMENT_STATUS_CHANGED = 'PAYMENT_STATUS_CHANGED',
    RESTAURANT_VERIFICATION_CHANGED = 'RESTAURANT_VERIFICATION_CHANGED',
    COURIER_VERIFICATION_CHANGED = 'COURIER_VERIFICATION_CHANGED',
    DELIVERY_PROBLEM_CREATED = 'DELIVERY_PROBLEM_CREATED',
    SYSTEM = 'SYSTEM',
}
